### ISSUE TITLE
Allow user choose frequency for loading new photos

### ISSUE THREAD

**Issue by sh4nks** [ayoisaiah/stellar-photos#12]
Would be cool to have an option which would let use use the same image the whole day.

Maybe you could also add a "quote of the day" a la Momentum Dash?

Nice extension btw!

**Comment by ayoisaiah** [comment]
Thank you! In a future release there would be an option to load photos every day or every hour in addition to the current behaviour.

For now, I don't have any plans to add quotes to the extension. But let's see if there are more requests for this.

**Comment by ayoisaiah** [comment]
![image](https://user-images.githubusercontent.com/13372163/32643005-7b3140e0-c5d8-11e7-8075-7a15125d7f8e.png)

**Comment by ayoisaiah** [comment]
![image](https://user-images.githubusercontent.com/13372163/32643128-83142f7e-c5d9-11e7-8738-e403df31b05d.png)

**Comment by ayoisaiah** [comment]
![image](https://user-images.githubusercontent.com/13372163/32644402-a9a5f3e0-c5e1-11e7-81f4-affe50e2b0a4.png)

**Comment by ayoisaiah** [comment]
https://github.com/ayoisaiah/stellar-photos/commit/7a5bc8787eddfef05bd816f3a4ee75cd795aa4ac
