### ISSUE TITLE
Remove Crying Man Picure

### ISSUE THREAD

**Issue by JonnyCodewalker** [ayoisaiah/stellar-photos#14]
Maybe just personal taste, but I use that extension to lighten my workload with the nice pictures. And the criyng man, as well made as that photo is is depressing. Not sure if it is fitting for the collection. https://imgur.com/a/7ytFg

**Comment by ayoisaiah** [comment]
@JonnyCodewalker Removed! In case you don't already know, you can curate your own collections on Unsplash and load photos from there as well. Just add the collection ID in the options.
