### ISSUE TITLE
Random image is not fetched

### ISSUE THREAD

**Issue by andreea93m** [ayoisaiah/stellar-photos#15]
I have been getting the same image for the last couple of days. It looks like the Unsplash API fails to return a random image from my collection:

![screenshot from 2017-10-16 20-13-57](https://user-images.githubusercontent.com/5804990/31627730-87798c96-b2ae-11e7-8ec6-9b649cd35363.png)

The request that fails: https://stellar-photos.herokuapp.com/api/photos/random/1266288
The collection: https://unsplash.com/collections/1266288

**Comment by ayoisaiah** [comment]
@andreea93m Thanks for reporting this. I am looking into it

**Comment by andreea93m** [comment]
@ayoisaiah It seems to be back to normal now

**Comment by ayoisaiah** [comment]
@andreea93m The problem was from Unsplash. I don't know why it was failing to retrieve photos from that collection. Glad to hear it's working now.
