### ISSUE TITLE
Extension path in Firefox address bar

### ISSUE THREAD

**Issue by terrakok** [ayoisaiah/stellar-photos#18]
![Screenshot of Issue](https://i.imgur.com/Mffduii.jpg)

**Comment by sorin-davidoi** [comment]
Might be a Firefox quirk/bug that has since been fixed? This is how it looks for me in Firefox Nightly.
![image](https://user-images.githubusercontent.com/2109702/32409346-4302b7a8-c1aa-11e7-9e34-4f38b1333332.png)

**Comment by terrakok** [comment]
I don't know. The problem is relevant on different devices.   
Firefox: Version 56.0.2 (64-bit)   
System: XUbuntu 16.04.3 LTS

**Comment by ayoisaiah** [comment]
@terrakok  This is a Firefox issue fixed in v57 which is shipping on November 14. Thanks.
