### ISSUE TITLE
Disable GA tracking

### ISSUE THREAD

**Issue by kanru** [ayoisaiah/stellar-photos#24]
Hi,

Your privacy policy states that

> Stellar Photos does not aggregate any user information.

But the new 2.0 update includes the GA script and is collecting usage data.

Please remove that feature or make it clear in the privacy policy what's being tracked.

**Comment by ayoisaiah** [comment]
Yeah I was going to get to that. It's updated now: https://github.com/ayoisaiah/stellar-photos/wiki/Privacy-Policy
