### ISSUE TITLE
Add info on which collection image is coming from

### ISSUE THREAD

**Issue by yonyonson** [ayoisaiah/stellar-photos#27]
### Issue

It is not always clear which collection picture is coming from, and why the given image is displayed at all.

### User need

User need a short explanation on why given image is displayed, and typical reason would be - since it is a part of collection "12345".

### Proposed solution

* We need an info on which collection image is coming from
* Information can be placed in "Photo info" page.
* That would be nice with a link to collection as well.

**Comment by ayoisaiah** [comment]
There is no way to determine which collection a photo is loaded from. Stellar only uses the provided collection IDs to narrow down the range of photos that can be loaded into the new tab. Unsplash does not attach any information about which collection a photo is actually coming from.
