### ISSUE TITLE
Address bar text is cleared when extension loads on Firefox

### ISSUE THREAD

**Issue by d53dave** [ayoisaiah/stellar-photos#33]
Hi,

I'm using the latest version of stellar photos with Firefox 80.0b8 (64-bit) on macOS 10.15.4, and I'm seeing this behavior now, which wasn't there before:

1. I open a new tab
2. I quickly start typing (Address bar is automatically focused when opening a new tab)
3. When stellar photos loads, the text I had already written into the address bar is deleted

I can trigger this behavior almost every time, but sometimes the extension loads really fast and it's not visible. I have a 2017 MBP 15, so performance should not be an issue.

**Comment by ayoisaiah** [comment]
Thank you for opening this issue. I've never noticed this issue in Firefox before, but I will investigate and get back to you soon.

**Comment by d53dave** [comment]
I tried to reproduce this with Firefox 79.0 (i.e., the normal one, not the developer edition) and it shows the same behaviour. I noticed it loads quite a bit faster on 79 than on 80.0b8, so it was more difficult to trigger the effect, but I still managed to run into it a few times.

**Comment by ayoisaiah** [comment]
I'm unable to reproduce this issue on Firefox 85. Feel free to reopen if the bug resurfaces
