### ISSUE TITLE
Official collections by unsplash

### ISSUE THREAD

**Issue by old-izayoi** [ayoisaiah/stellar-photos#34]
Is there any way to not make a new collection and add anything 1 by 1? i want to add https://unsplash.com/t/nature, but there is no ID for that

**Comment by ayoisaiah** [comment]
I'm not sure it's possible to access those sort of collections through the public API, but will investigate further.

You can create your own collections by clicking the + button that appears when you hover your cursor on the image. Your collection would be given an ID which you can add to the extension.
