### ISSUE TITLE
Background Images not sharp enough on hi-res monitors

### ISSUE THREAD

**Issue by ayoisaiah** [ayoisaiah/stellar-photos#4]
Need to load a higher resolution of the image as the background image as the current versions aren't sharp enough

![image]()

**Comment by StuartMorrisAU** [comment]
Hi there,

I just installed this extension and have found the images to all be quite low res/ not sharp enough on my display (2560x1440 Dell U2715H), and noticeably different to the source image.

**Comment by ayoisaiah** [comment]
Hi @StuartMorrisAU, the images that are being loaded are 1500px in width which should be sufficient for the majority of users. What image resolution do you find to be acceptable on your display?
