### ISSUE TITLE
Photos not updating, getting error when changing sets

### ISSUE THREAD

**Issue by yonyonson** [ayoisaiah/stellar-photos#52]
Several days ago photos stopped rotating. When trying to change sets that are in use, or switch to defult photo set I get an excetion "TypeError: NetworkError when attempting to fetch resource." as a red popup within settings for plugin.

The rest of browser works, stellar photos is the only part of browser that stopped working.

How can I debug further?

My env:
FF 96.0.2
macOS 12.1

**Comment by ayoisaiah** [comment]
Sorry, it's a server issue. I'll deploy a fix shortly

**Comment by ayoisaiah** [comment]
I just released an updated on all the platforms, it should come through to you soonest. Thanks!

**Comment by yonyonson** [comment]
Thanks! Its gone now :)
