### ISSUE TITLE
Settings Button is Missing

### ISSUE THREAD

**Issue by anthonylavado** [ayoisaiah/stellar-photos#57]
Hey there!
I just realized that the options/settings button isn't visible on my install. Is this currently removed/disabled?

**Browser:**
Firefox 100.0.1

**Operating System:**
Windows 10 (21H2, build 19044.1645)

**Comment by ayoisaiah** [comment]
Do you mean this?
![image](https://user-images.githubusercontent.com/13372163/169030965-1896a3ff-a493-4555-a879-80f5d033d83d.png)

**Comment by anthonylavado** [comment]
Ah my mistake. I was looking for a gear icon next to the other options. Thanks!
