### ISSUE TITLE
Fade in/out the buttons and bars

### ISSUE THREAD

**Issue by forteller** [ayoisaiah/stellar-photos#6]
Loving this! Thanks!

Only thing is that I find the buttons in the corner and bar at the bottom distracting from the overall very nice and clean look. I'd love it if these where hidden by default and faded in when moving the mouse closer to them, like in [Art up your tab](http://www.art-tab.eu/). :)

**Comment by ayoisaiah** [comment]
I'll add an option to enable this in the next release.

**Comment by forteller** [comment]
Awesome! Thanks! :)

**Comment by ayoisaiah** [comment]
@sorin-davidoi I like the idea of fading in the controls when you move the mouse near them just like Art up your Tab referenced above and then the history images would be loaded only when the hambuger menu is clicked.

**Comment by ayoisaiah** [comment]
https://github.com/ayoisaiah/stellar-photos/commit/581b390d7f714b1cae18ddbe2c810bf0e369604e
