### ISSUE TITLE
Noticeable lag before photo is loaded into new tab page

### ISSUE THREAD

**Issue by forteller** [ayoisaiah/stellar-photos#7]
My internet is not very fast. So when I open a new tab the background is completely black for a while before the pic loads. Mostly I know where I want to go when I open a new tab, so I just see the black before I go to my next destination.

It would be nice if when I open a new tab it would download the _next_ picture to show me, that is the one that will be used the next time I open a new tab. That way the picture could load instantly when I open a new tab, and not wait to download. Just download the next pic in the background :)

**Comment by ayoisaiah** [comment]
I've not been able to reproduce this. The next photo is already loaded in the background when you open a new tab so everything should work seamlessly. If your internet is not fast, you may see the same image across multiple new tabs but not a black background.

The only time you may see a black background is when the extension is first installed and the first image hasn't loaded yet.

**Comment by forteller** [comment]
Here, have a look at how it is for me, every time: https://imgur.com/GOYWqFj

**Comment by ayoisaiah** [comment]
@forteller Ok I see what you mean. The problem is not that the photos aren't preloaded, it's just not loaded into the new tab page fast enough. I will look into it and try to fix it soon

**Comment by forteller** [comment]
Thank you! :)

**Comment by ayoisaiah** [comment]
@forteller The latest release 1.11.40 should fix this issue.
